# Installs Prometheus Stack
---
- hosts: all
  become: yes
  vars:
    prometheus_version: "2.9.1"
    prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prom_base_dir: "/srv/apps"
    prom_cfgs_repo: "https://github.com/flash1194/prometheus-configs.git"
    prom_cfgs_dir: "/srv/cfgs/prometheus-configs"

  tasks:
    - name: Prometheus | Create appropriate base folder structure
      file:
        path: "{{ prom_base_dir }}"
        state: directory
        mode: 0755
      
    - name: Prometheus | Create service account
      user:
        name: prometheus

    - name: Prometheus | Clone configs
      git:
        repo: "{{ prom_cfgs_repo }}"
        dest: "{{ prom_cfgs_dir }}"

    - name: Prometheus | Create systemd file
      copy:
        src: "{{ prom_cfgs_dir }}/prometheus.service"
        dest: "/etc/systemd/system/"
        remote_src: yes
        
    - name: Prometheus | Download and unpack
      unarchive:
        src: "{{ prometheus_download_url }}"
        dest: "{{ prom_base_dir }}"
        remote_src: yes
    
    - name: Prometheus | Rename directory for simplicity
      command: "mv {{ prom_base_dir }}/prometheus-{{ prometheus_version }}.linux-amd64 {{ prom_base_dir }}/prometheus"

    - name: Prometheus | Make service account owner of Prometheus application directory
      file:
        path: "{{ prom_base_dir }}/prometheus"
        owner: prometheus
        group: prometheus
        recurse: yes
        mode: 0777
    
    - name: Prometheus | Make service account owner of Prometheus configurations directory
      file:
        path: "{{ prom_cfgs_dir }}"
        owner: prometheus
        group: prometheus
        recurse: yes
        mode: 0777

    - name: Prometheus | Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes